BEGIN;

CREATE TABLE shot_molds (
  id BIGSERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE shot_records (
  id BIGSERIAL PRIMARY KEY,
  mold_id BIGINT NOT NULL REFERENCES shot_molds(id) ON DELETE CASCADE,
  recorded_on DATE NOT NULL,
  shot_count BIGINT NOT NULL CHECK (shot_count > 0),
  notes TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMIT;
